name: Update Strava Latest Run

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  update-strava:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # allows pushing with GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python fetch_strava_latest.py
          ls -l data || true
          echo "If script printed NEW_REFRESH_TOKEN above, update your repository secret STRAVA_REFRESH_TOKEN with that value."

      - name: Commit and push changed data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/latest_run.json data/latest_route.geojson || true
          git commit -m "Update Strava latest run" || echo "No changes to commit"
          git push
